---
- name: reconfigure gitlab
  raw: gitlab-ctl reconfigure
  become: yes
  become_method: sudo

- name: Copy nginx gitlab configuration
  template: src=nginx_gitlab_config dest=/etc/nginx/sites-enabled/gitlab owner=root group=root
  become: yes
  become_method: sudo

- name: restart nginx
  service: name=nginx state=restarted enabled=yes
  become: yes
  become_method: sudo
